site_name: AsBuiltReport
site_author: Tim Carman
site_description: Document Your Datacenter With PowerShell
repo_url: https://github.com/AsBuiltReport/AsBuiltReport.github.io
theme:
    name: material
    logo: https://raw.githubusercontent.com/AsBuiltReport/AsBuiltReport/master/AsBuiltReport.png
    favicon: https://raw.githubusercontent.com/AsBuiltReport/AsBuiltReport/master/AsBuiltReport.png
    features:
      - content.code.annotate
      - navigation.sections
    palette:
      primary: amber
    locale: en
    highlightjs: true
    icon:
      repo: fontawesome/brands/github
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - New-AsBuiltConfig: user-guide/new-asbuiltconfig.md
    - New-AsBuiltReport: user-guide/new-asbuiltreport.md
    - New-AsBuiltReportConfig: user-guide/new-asbuiltreportconfig.md
  - Developer Guide:
    - Report Modules: dev-guide/report-modules.md
    - Contributing: dev-guide/contributing.md
  - Support:
    - FAQ: support/faq.md
    - Donate: support/donate.md
  - About:
    - Contact: about/contact.md
    - Acknowledgements: about/acknowledgements.md